language: node_js
node_js:
  - "10"

dist: trusty
sudo: false
addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

install:

before_script:
  - npm audit

script:
  - npm run audit:process
