language: node_js
node_js:
  - "10"

dist: trusty
sudo: false
addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

install:
  - npm install
  - npm run build

before_script:
  - echo $TRAVIS_BUILD_DIR/
  - $TRAVIS_BUILD_DIR/npm-audit-practice/audit/audit-no-exit-code.sh

script:
  - npm run audit:process
